name: zyj_pytorch
channels:
  - dglteam/label/th24_cu121
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - certifi=2025.10.5=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9c0eb46_1
  - dbus=1.16.2=h5bd4931_0
  - dgl=2.4.0.th24.cu121=py310_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py310hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jpeg=9f=h5ce9db8_0
  - jsonlines=4.0.0=py310h06a4308_0
  - kiwisolver=1.4.8=py310h6a678d5_0
  - krb5=1.20.1=h568e23c_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=ha637b67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm14=14.0.6=hef93074_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.6=py310h06a4308_0
  - matplotlib-base=3.10.6=py310h71dd3da_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.4.0=py310h5eee18b_3
  - mkl_fft=1.3.11=py310hacdc0fc_1
  - mkl_random=1.2.8=py310h2fd27a0_1
  - mysql=5.7.24=he378463_2
  - ncurses=6.5=h7934f7d_0
  - numexpr=2.11.0=py310h397f862_1
  - numpy=1.26.4=py310h64c44e4_1
  - numpy-base=1.26.4=py310he1678cf_1
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=1.1.1w=h7f8727e_0
  - packaging=25.0=py310h06a4308_0
  - pandas=2.3.2=py310h277b779_0
  - pcre=8.45=h295c915_0
  - pip=25.2=pyhc872135_0
  - ply=3.11=py310h06a4308_0
  - psutil=7.0.0=py310hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyqt=5.15.10=py310h6a678d5_1
  - pyqt5-sip=12.13.0=py310h5eee18b_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.0=h12debd9_5
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py310h06a4308_0
  - qt-main=5.15.2=h110a718_10
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_0
  - scipy=1.15.3=py310h0a862cd_1
  - sip=6.7.12=py310h6a678d5_1
  - six=1.17.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py310h06a4308_0
  - tornado=6.5.1=py310h5eee18b_0
  - tqdm=4.67.1=py310h2f386ee_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.3.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - alembic==1.17.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - cffi==2.0.0
      - click==8.3.0
      - colorlog==6.10.1
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.13.1
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.4
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - ipykernel==7.0.1
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - jiter==0.12.0
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - lark==1.3.1
      - lightning-utilities==0.15.2
      - mako==1.3.10
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mistune==3.1.4
      - mpmath==1.3.0
      - multidict==6.6.4
      - narwhals==2.10.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai==2.8.1
      - optuna==4.5.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pastel==0.2.1
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.5.0
      - plotly==6.3.1
      - poethepoet==0.10.0
      - pot==0.9.6.post1
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.0
      - protobuf==6.33.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-json-logger==4.0.0
      - pytorch-lightning==2.5.5
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.29.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.42.1
      - setuptools==80.9.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - stack-data==0.6.3
      - sympy==1.13.3
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - tomlkit==0.13.3
      - torch==2.4.0+cu121
      - torch-geometric==2.6.1
      - torchaudio==2.4.0+cu121
      - torchcde==0.2.5
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchmetrics==1.8.2
      - torchsde==0.2.6
      - torchvision==0.19.0+cu121
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.40.1
      - triton==3.0.0
      - typing-extensions==4.12.2
      - uri-template==1.3.0
      - wandb==0.22.2
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.14
      - yarl==1.21.0
prefix: /home/common/anaconda3/envs/zyj_pytorch
